version: '3.1'

services:
  mosquitto:
    image: eclipse-mosquitto:latest
    restart: on-failure
    volumes:
      - ./mosquitto.conf:/mosquitto/config/mosquitto.conf
    ports:
      - 1883:1883
      - 9001:9001
      - 8080:8080